[package]
name = "knuth-bendix"
description = "Placeholder for Knuth-Bendix"
license = "Apache-2.0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
